default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: urutora15872
  socket: /tmp/mysql.sock


development:
  <<: *default
  database: maker_development


test:
  <<: *default
  database: maker_test

production:
  <<: *default
  database: sample
  username: root
  password: urutora15872
  socket: /var/lib/mysql/mysql.sock                          